name: entityfy_workspace
description: A monorepo workspace for the Entityfy package ecosystem
version: 2.0.1
homepage: https://github.com/Sirtoolkit/entityfy
repository: https://github.com/Sirtoolkit/entityfy

environment:
  sdk: ^3.8.0

dependencies:
  melos: ^6.3.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2