name: entity_mapper_generator
description: A powerful Dart code generator that automatically creates toEntity() methods for seamless conversion between domain models and data layer entities using simple annotations.
version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  source_gen: ^2.0.0
  build_runner: ^2.4.15
  build: ^2.5.4
  analyzer: ^7.7.0