name: entityfy
version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  source_gen: ^2.0.0
  build: ^2.5.4
  analyzer: ^7.0.0
  meta: ^1.16.0
  melos: ^6.3.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
  build_runner: ^2.5.4