builders:
  entityfy_combined:
    import: "package:entityfy_generator/src/entityfy_generator.dart"
    builder_factories: ["combinedEntityfyGenerator"]
    build_extensions: { ".dart": [".entityfy.g.dart"] }
    auto_apply: dependents
    build_to: source
