builders:
  entityfy_generator:
    import: "package:entityfy_generator/src/mapper_generator.dart"
    builder_factories: ["entityfyGenerator"]
    build_extensions: {".dart": [".mapper.g.dart"]}
    auto_apply: dependents
    build_to: source